### ISSUE TITLE
Error on Windows 11 - Readline

### ISSUE THREAD

**Issue by Capitaplc** [s41r4j/phomber#11]
![image](https://github.com/s41r4j/phomber/assets/108936672/50d3c81a-02fc-4833-863b-1a54c279798c)

**Comment by Alomac88** [comment]
That module seems not working under Windows.

**Comment by s41r4j** [comment]
Hello everyone!

I have updated the code with `readline`'s alternative `prompt_toolkit`!
(pls update your code 1 day after of this msg)

Have a good day!

**Comment by Oqarshi** [comment]
> 

can i know where the code is?

**Comment by s41r4j** [comment]
> **Hey!**
> 
> I have updated the code with `readline`'s alternative `prompt_toolkit`! The code isn't tested with windows, pls report any bugs/abnormalities you may find!
> 
> Have a good day!

*
