### ISSUE TITLE
[!] An error occured: module 'readline' has no attribute 'parse_and_bind'

### ISSUE THREAD

**Issue by Charlies-Kvit** [s41r4j/phomber#13]
[!] An error occured: module 'readline' has no attribute 'parse_and_bind'

**Comment by Oqarshi** [comment]
yes i think the module readline isnt availbale on windows

**Comment by s41r4j** [comment]
yupp readline module is not avaliable on windows!
I have upgraded from readline to a different library, will soon upgrade the phomber with it!

Thankyou :)
