### ISSUE TITLE
Code Review 

### ISSUE THREAD

**Issue by ArkAngeL43** [s41r4j/phomber#2]
I like the tool, over all you have GREAT code, great functionality, and even organizations, I also see everything under a definition and call it with if name in main, like seeing it 

however one thing I noticed is you have 
‘’’python

import phonenumbers, sys, datetime, progressbar, time, mechanize, os

‘’’

this is a good strategy however it can slow down the scripts runtime, a better opposition would be 

‘’’python
Import sys 
Import os 
Import date time 
Etc 
‘’’

just something to make the runtime a bit better, but everything else looks fine, nice job!

**Comment by s41r4j** [comment]
@ArkAngeL43 , Hey !

Thanks for reviewing code !
I'll surely see to it .

(**Blooper alert**) I'm right trying to improve code structure and bring u a direct - CLI - program

**Comment by ArkAngeL43** [comment]
ofc! if you neeed help with the project let me know and we can chat over discord or something to plan ways to make it a better script

**Comment by s41r4j** [comment]
@ArkAngeL43  - OR anyone, who want to contribute to any project - I'm Building a discord  server - soon will be available on profile (special repo) . Hey till we can discuss on Instagram !! Please DM me (anyone who is interested) on my Instagram [@s41r4j](https://www.instagram.com/s41r4j)

**Comment by benja902** [comment]
hello friend thanks for all the support I wanted to tell you my problem
> since in the last step to locate the phone I get this

>Traceback (most recent call last):
  File "/home/kali/Desktop/phomber/phomber.py", line 21, in <module>
    import phonenumbers, sys, datetime, progressbar, time, mechanize, os
ModuleNotFoundError: No module named 'progressbar'

I don't know if you could help me, thanks

**Comment by s41r4j** [comment]
@benja902 The error says everything!
You don't have a module (`ModuleNotFoundError` last line) installed needed for the program to run, named `progressbar`.
Therefore in python you can install an module with `pip`
you just need to type command in cmd (for windows) or terminal (for linux/unix) [same command for both] : 
`pip install progressbar`

**Comment by benja902** [comment]
@s41r4j I already did it but I get the same error
![image](https://user-images.githubusercontent.com/98481542/164484044-234f3fe9-abd5-4bf5-b05c-2b854efa0806.png)

**Comment by ArkAngeL43** [comment]
did you do pip3? sometimes that works

**Comment by benja902** [comment]
@s41r4j I was able to do it thanks for the instructions
