### ISSUE TITLE
Invalid api key

### ISSUE THREAD

**Issue by Greenbird87** [s41r4j/phomber#3]
Hey

Thank you for your application
I followed your tutorial on how to add the api key but it still says entered invalid api key

[Screenshot_2022-02-09_04-07-14](https://user-images.githubusercontent.com/99305848/153114365-047908b8-2843-4cc6-8a97-141594746bee.png)

key = 'xxxxx....'

I also tried with double "xxx.."

**Comment by s41r4j** [comment]
Thank for reporting this !

I'll try to resolve the error, till check if this [issue](https://github.com/s41r4j/phomber/issues/1) helps.

**Comment by wtroisey** [comment]
I also encounter this error - is there any update on this?

**Comment by s41r4j** [comment]
Because of updates in dependencies, some features of tool are broken.
Have some other work - so the development of [v.3] is slow till time.

**Comment by EnterTheScanlines** [comment]
@s41r4j 
I have the same problem my friend
thanks for the app hopefully you can repair the problem
![Screenshot_2022-04-21_05_39_30](https://user-images.githubusercontent.com/104111306/164804861-446aacda-ae73-4bad-8311-3382f14de529.png)

**Comment by Andrejki** [comment]
Hi. The same error. 
Best regards.

**Comment by s41r4j** [comment]
Sorry everyone for delay!
PH0MBER v3 has been release, which is free from __API keys__ 
Try out new version (which is now a osint framework)

Thankyou :)

**Comment by EnterTheScanlines** [comment]
thanks man!!
