### ISSUE TITLE
OpenCage Geolocation Feature

### ISSUE THREAD

**Issue by freyfogle** [s41r4j/phomber#4]
Hi, 

Ed from OpenCage here. 

I'm sorry but this tool is not real. All you are doing is determining the country of the phone number from the country code and then geocoding the country name. Obviously we then return the coordinates of the center of the country. 

Please can you clarify in the README that this script absolutely will NOT tell you the location of a phone. We are getting a lot of confused and angry people asking us for support and wondering why they can't track a phone.

Thanks

**Comment by s41r4j** [comment]
Hey Ed,

Thank you for raising this issue!
I agree with you - and in version (v.3) I'll mention in tool (or remove) about this thing.
Till the time, v.3 is been developed this issue will be OPEN.

And this is not MISLEADING as I haven't mentioned anywhere that it gives exact location of the phone number.
Anyways, I'll mention that !!

Have a nice day :)

**Comment by s41r4j** [comment]
Many user seems confused with API keys (etc;)
PH0MBER next gen (v3) has been released free of any API keys (etc;)
