### ISSUE TITLE
osx version is failing

### ISSUE THREAD

**Issue by alonsoir** [s41r4j/phomber#6]
┌<▸> ~ 
└➤ pip install phomber
ERROR: Could not find a version that satisfies the requirement phomber (from versions: none)
ERROR: No matching distribution found for phomber
┌<▪> ~ 
└➤ pip --version      
pip 22.3 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by AdrienMasanet** [comment]
Same issue here !
